import type { VacancyWithDynamics } from "./model/types";
import type { VacancyWithExperience } from "./model/types";

export const test_vacancies: VacancyWithExperience[] = [
  {
    id: 1,
    title: "Frontend Developer",
    description: "Создавать интерфейсы и компоненты",
    company: "Tech Corp",
    salary: "120000 тенге",
    city: "Москва",
    key_skills: ["React", "TypeScript", "CSS"],
    minExperience: 3,
    dynamics: [
      { count: 1200, month: "Янв", year: 2024 },
      { count: 1450, month: "Фев", year: 2024 },
      { count: 1680, month: "Мар", year: 2024 },
      { count: 1920, month: "Апр", year: 2024 },
      { count: 2100, month: "Май", year: 2024 },
      { count: 2350, month: "Июн", year: 2024 },
    ],
  },
  {
    id: 2,
    title: "Backend Developer",
    description: "Разработка серверной части приложений",
    company: "Data Systems",
    salary: "130000 - 140000 евро",
    city: "Санкт-Петербург",
    key_skills: ["Node.js", "Express", "PostgreSQL"],
    minExperience: 2,
    dynamics: [
      { count: 900, month: "Янв", year: 2024 },
      { count: 950, month: "Фев", year: 2024 },
      { count: 970, month: "Мар", year: 2024 },
      { count: 915, month: "Апр", year: 2024 },
      { count: 920, month: "Май", year: 2024 },
      { count: 938, month: "Июн", year: 2024 },
    ],
  },
  {
    id: 3,
    title: "QA инженер",
    description: "Тестирование программного обеспечения",
    company: "QualityWorks",
    salary: "90000 руб",
    city: "Новороссийск",
    key_skills: ["Selenium", "Jest", "Git"],
    minExperience: 5,
    dynamics: [
      { count: 500, month: "Янв", year: 2024 },
      { count: 600, month: "Фев", year: 2024 },
      { count: 620, month: "Мар", year: 2024 },
      { count: 630, month: "Апр", year: 2024 },
      { count: 640, month: "Май", year: 2024 },
      { count: 670, month: "Июн", year: 2024 },
    ],
  },
  {
    id: 4,
    title: "Data Scientist",
    description: "Анализ данных и построение ML-моделей",
    company: "AI Solutions",
    salary: "150000 белорусских рублей",
    city: "Москва",
    key_skills: ["Python", "TensorFlow", "SQL", "Pandas"],
    minExperience: 2,
    dynamics: [
      { count: 800, month: "Янв", year: 2024 },
      { count: 950, month: "Фев", year: 2024 },
      { count: 1100, month: "Мар", year: 2024 },
      { count: 1250, month: "Апр", year: 2024 },
      { count: 1400, month: "Май", year: 2024 },
      { count: 1550, month: "Июн", year: 2024 },
    ],
  },
  {
    id: 5,
    title: "DevOps Engineer",
    description: "Настройка CI/CD и облачной инфраструктуры",
    company: "CloudTech",
    salary: "140000 - 500000 рублей",
    city: "Санкт-Петербург",
    key_skills: ["Docker", "Kubernetes", "AWS", "Jenkins"],
    minExperience: 4,
    dynamics: [
      { count: 600, month: "Янв", year: 2024 },
      { count: 720, month: "Фев", year: 2024 },
      { count: 810, month: "Мар", year: 2024 },
      { count: 890, month: "Апр", year: 2024 },
      { count: 950, month: "Май", year: 2024 },
      { count: 1020, month: "Июн", year: 2024 },
    ],
  },
  {
    id: 6,
    title: "Fullstack Developer",
    description: "Разработка полного цикла веб-приложений",
    company: "WebInnovations",
    salary: "135000 тенге",
    city: "Екатеринбург",
    key_skills: ["JavaScript", "React", "Node.js", "MongoDB"],
    minExperience: 3,
    dynamics: [
      { count: 1100, month: "Янв", year: 2024 },
      { count: 1250, month: "Фев", year: 2024 },
      { count: 1380, month: "Мар", year: 2024 },
      { count: 1520, month: "Апр", year: 2024 },
      { count: 1650, month: "Май", year: 2024 },
      { count: 1780, month: "Июн", year: 2024 },
    ],
  },
  {
    id: 7,
    title: "Mobile Developer",
    description: "Разработка мобильных приложений для iOS и Android",
    company: "AppCraft",
    salary: "125000 - 200000 евро",
    city: "Москва",
    key_skills: ["React Native", "Swift", "Kotlin", "Redux"],
    minExperience: 2,
    dynamics: [
      { count: 700, month: "Янв", year: 2024 },
      { count: 820, month: "Фев", year: 2024 },
      { count: 910, month: "Мар", year: 2024 },
      { count: 980, month: "Апр", year: 2024 },
      { count: 1050, month: "Май", year: 2024 },
      { count: 1120, month: "Июн", year: 2024 },
    ],
  },
  {
    id: 8,
    title: "UX/UI Designer",
    description: "Проектирование пользовательских интерфейсов",
    company: "DesignStudio",
    salary: "100000 руб",
    city: "Санкт-Петербург",
    key_skills: ["Figma", "Adobe XD", "User Research", "Prototyping"],
    minExperience: 2,
    dynamics: [
      { count: 850, month: "Янв", year: 2024 },
      { count: 920, month: "Фев", year: 2024 },
      { count: 980, month: "Мар", year: 2024 },
      { count: 1040, month: "Апр", year: 2024 },
      { count: 1100, month: "Май", year: 2024 },
      { count: 1150, month: "Июн", year: 2024 },
    ],
  },
  {
    id: 9,
    title: "Product Manager",
    description: "Управление продуктом и разработка стратегии",
    company: "ProductLabs",
    salary: "160000 евро",
    city: "Москва",
    key_skills: ["Agile", "Analytics", "Roadmapping", "A/B Testing"],
    minExperience: 5,
    dynamics: [
      { count: 400, month: "Янв", year: 2024 },
      { count: 450, month: "Фев", year: 2024 },
      { count: 480, month: "Мар", year: 2024 },
      { count: 520, month: "Апр", year: 2024 },
      { count: 550, month: "Май", year: 2024 },
      { count: 580, month: "Июн", year: 2024 },
    ],
  },
  {
    id: 10,
    title: "System Administrator",
    description: "Обслуживание IT-инфраструктуры компании",
    company: "ITSupport Pro",
    salary: "80000 долларов",
    city: "Новосибирск",
    key_skills: ["Linux", "Windows Server", "Networking", "Bash"],
    minExperience: 3,
    dynamics: [
      { count: 1200, month: "Янв", year: 2024 },
      { count: 1250, month: "Фев", year: 2024 },
      { count: 1220, month: "Мар", year: 2024 },
      { count: 1180, month: "Апр", year: 2024 },
      { count: 1150, month: "Май", year: 2024 },
      { count: 1120, month: "Июн", year: 2024 },
    ],
  },
];